# Generated by Django 2.1.4 on 2019-01-06 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('expire_to', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('login_type', models.CharField(choices=[(1, 'MOBILE'), (2, 'EMAIL'), (3, 'WX')], max_length=1, verbose_name='登录类型')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('open_id', models.CharField(max_length=20, verbose_name='微信ID')),
                ('password', models.CharField(max_length=100, verbose_name='登录密码')),
                ('nickname', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('avatar', models.ImageField(default='xxx', null=True, upload_to='avatar', verbose_name='头像')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('create_date', models.DateField(verbose_name='创建日期')),
                ('last_login_date', models.DateField(verbose_name='最后登录日期')),
                ('last_login_ip', models.GenericIPAddressField(null=True, verbose_name='最后登录IP')),
            ],
        ),
        migrations.AddField(
            model_name='tokens',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Users'),
        ),
    ]
