# Generated by Django 2.1.4 on 2019-01-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='user_id',
            new_name='user',
        ),
    ]
