# Generated by Django 2.1.4 on 2019-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190106_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
    ]
