# Generated by Django 2.1.5 on 2019-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190106_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='login_type',
            new_name='signup_type',
        ),
    ]
