# Generated by Django 2.1.4 on 2019-01-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190107_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokens',
            options={'verbose_name': '密码表', 'verbose_name_plural': '密码表'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
