# Generated by Django 2.1.4 on 2018-12-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinformation',
            old_name='cover',
            new_name='book_cover',
        ),
    ]
