# Generated by Django 2.1.4 on 2018-12-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInfo',
            new_name='BookInformation',
        ),
    ]
