# Generated by Django 2.1.4 on 2019-01-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20190112_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='无效', max_length=10, verbose_name='课程类型')),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='旅行瑜伽', max_length=100, verbose_name='课程标题')),
                ('picture', models.ImageField(default='show.jpg', upload_to='curricula', verbose_name='展示图片')),
                ('desc', models.CharField(max_length=640, null=True, verbose_name='课程描述')),
                ('start_time', models.DateTimeField(null=True, verbose_name='上课时间')),
                ('duration', models.IntegerField(null=True, verbose_name='授课时长')),
                ('status', models.IntegerField(null=True, verbose_name='课程状态')),
                ('location', models.CharField(max_length=512, null=True, verbose_name='授课地点')),
                ('category', models.ForeignKey(default=1, on_delete=None, to='curriculum.Cat1', verbose_name='课程类型')),
                ('coach', models.ForeignKey(default=1, on_delete=None, related_name='curriculum', to='account.Users', verbose_name='教练')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
    ]
