# Generated by Django 2.1.4 on 2019-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Curricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='课程标题')),
                ('desc', models.CharField(max_length=640, null=True, verbose_name='课程描述')),
                ('duration', models.IntegerField(null=True, verbose_name='授课时长')),
                ('status', models.IntegerField(null=True, verbose_name='课程状态')),
                ('location', models.CharField(max_length=512, null=True, verbose_name='授课地点')),
            ],
        ),
    ]
