# Generated by Django 2.1.4 on 2019-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190107_1144'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curricula',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=None, to='account.Users'),
        ),
    ]
