# Generated by Django 2.1.4 on 2019-01-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat1',
            options={'verbose_name': '课程类型', 'verbose_name_plural': '课程类型'},
        ),
    ]
