# Generated by Django 2.1.4 on 2019-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20190112_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat1',
            name='category_name',
            field=models.CharField(default='输入名称', max_length=10, verbose_name='课程类型'),
        ),
        migrations.AlterField(
            model_name='curricula',
            name='title',
            field=models.CharField(default='输入课程标题', max_length=100, verbose_name='课程标题'),
        ),
    ]
