# Generated by Django 2.1.4 on 2019-01-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_curricula_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat1',
            name='description',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
