# Generated by Django 2.1.4 on 2019-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_cat1_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curricula',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=None, related_name='curriculum', to='account.Users'),
        ),
    ]
